name: Z-Calling
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  # System & Build Tools
  - python=3.10          # Staying on 3.10 is safest for C++ compilation
  - pip
  - htslib
  - zlib
  - libsvm
  - cmake
  - make
  - cxx-compiler
  - pbmm2                # <--- ADDED: PacBio wrapper for minimap2
  
  # Python Packages
  - pip:
    - numpy<2.0          # Strictly required for PyTorch compatibility
    - pandas
    - pysam
    - --index-url https://download.pytorch.org/whl/cpu
    - torch==2.2.2       # Stable, bug-free release
